### ISSUE TITLE
Sponsor Meta does not Save. Also, how to reorganize Sponsors?

### ISSUE THREAD

**Issue by marieepicraces** [realbig/RBM_TH_EPIC#137]
I just went into the back-end to remove some old sponsors from our home page, using the slider box on their partner page as instructed. When I checked the home page, they are still showing up. 

Can you look into this and also let me know how I can reorder the sponsors? I need American Home Fitness, Probility and Suburban to be at the top of the grouping, and if possible, larger. 

Thanks.

**Comment by d4mation** [comment]
I just pushed a minor fix to support this on the Home Page.

Firstly, you will want to expand "Screen Options" at the top of the Admin Screen when viewing the Partners and set the "Number of items per page" value higher. You may only want to do this temporarily as it is set to 20 for performance reasons.

![image](https://user-images.githubusercontent.com/7770631/45384397-f5bbf000-b5db-11e8-8594-1e1126624c26.png)

Then, you can simply drag and drop them in the order that you'd like. Whichever appears first in this list will appear first on the Home Page.

![image](https://i.imgur.com/keXfW3v.gif)

**Comment by marieepicraces** [comment]
This is helpful for re-ordering but you still have a problem with the show
on home page slider. It doesn't seem to work. I can't *add* American Home
Fitness and I can take off the sponsors I don't want to see....

Is this because I'm using a Chromebook, or is this a glitch?

Thanks!

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com

**Comment by d4mation** [comment]
Thank you for pointing that out, there was indeed a bug regarding that portion of it. I just pushed a fix which should allow you to both Add and Remove Sponsors from the Home Page properly.

Again, thank you for your patience.

**Comment by marieepicraces** [comment]
Thanks! Seems to have done the trick.

Marie Brooks

*Charity Champion & Registration Director*


p: 734.585.7101 ext. 708 a: 600 South Wagner, Ann Arbor, MI 48103

w: epicraces.com <https://www.epicraces.com/> e: marie@epicraces.com
